web/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace web.Models{
    public class Message{
        public int ID { get; set;}
        public String Name { get; set; }
        public String Text { get; set; }
        public DateTime TimeStamp { get; set; }

        public int ChatID { get; set; }

    }
}

web/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;
using Microsoft.AspNetCore.Authorization;

namespace web.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        
        private readonly PostContext _context;

        public MessagesController(PostContext context)
        {
            _context = context;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            return View(await _context.Message.ToListAsync());
        }

        [HttpPost]
        public async Task <IActionResult> CreateRoom(string name){

            _context.Chats.Add(new Chat{
                Name = name
            });

            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Message
                .FirstOrDefaultAsync(m => m.ID == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Text,TimeStamp")] Message message)
        {
            if (ModelState.IsValid)
            {
                _context.Add(message);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Message.FindAsync(id);
            if (message == null)
            {
                return NotFound();
            }
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Text,TimeStamp")] Message message)
        {
            if (id != message.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(message);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessageExists(message.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Message
                .FirstOrDefaultAsync(m => m.ID == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var message = await _context.Message.FindAsync(id);
            _context.Message.Remove(message);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MessageExists(int id)
        {
            return _context.Message.Any(e => e.ID == id);
        }

        [HttpPost]

        public async Task<IActionResult> Creat1eRoom (String name){
            _context.Chats.Add(new Chat{
                Name = name,

            });

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

web/ViewComponents/RoomViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using web.Data;
using System.Linq;
using web.Migrations;

namespace web.ViewComponents {
    public class RoomViewComponent: ViewComponent{
        private readonly PostContext _context;

        public RoomViewComponent (PostContext context){
            _context = context;
        }
        public IViewComponentResult Invoke(){

        var chats = _context.Chats.ToList();
        return View();
    }

    }

    
} 

web/Views/Messages/Create.cshtml
@model web.Models.Message

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Message</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeStamp" class="control-label"></label>
                <input asp-for="TimeStamp" class="form-control" />
                <span asp-validation-for="TimeStamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Messages/Delete.cshtml
@model web.Models.Message

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

web/Views/Messages/Details.cshtml
@model web.Models.Message

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Messages/Edit.cshtml
@model web.Models.Message

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Message</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeStamp" class="control-label"></label>
                <input asp-for="TimeStamp" class="form-control" />
                <span asp-validation-for="TimeStamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Messages/Index.cshtml
@using web.Models;
@model IEnumerable<Message>



<!--h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="message_menu_body">

    <!--div class = "navigation_bar">

    </div-->

    <div class = "message_menu">
        <vc:room></vc:room>
        <div class="chat">
            <div class="chat-body">
                <div class="message">
                    <header><strong>Test1</strong></header>
                    <p> This is a test message</p>
                    <footer>15:42</footeer>
                </div>

                <div class="message">
                    <header><strong>Test2</strong></header>
                    <p> This is a test message number 2</p>
                    <footer>15:45</footeer>
                </div>

                <div class = "modal" id = "create-room-modal">
                    <div class = "modal-body">
                        <form asp-action="CreateRoom" asp-controller="Messages" class ="">
                            
                            <button class ="close_modal" type="button" onclick="closeModal()">X</button> 
                            <header>Create Room</header>
                            <div>
                                <input name = "name">
                            </div>
                            <footer><button>Create</button></footer>


                        </form>
                    </div>
                    
                </div>
            </div>
            <div class="chat-input">
                <form class ="send_message">
                    <input type="text" />
                    <button>Send</button>
                </form>
                

            </div>
        </div>
    </div>

</table>

<script src ="~/js/site.js"></script>